package com.android.todoapp.data.local

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.android.todoapp.util.Constants.TASK_TABLE
import kotlinx.parcelize.Parcelize
/**
 * TaskEntry is a data class representing a task entity in the database.
 * It implements [Parcelable] to allow for object serialization and deserialization.
 *
 * @property id The unique identifier of the task. This is autogenerated and serves as the primary key.
 * @property title The title of the task.
 * @property priority The priority level of the task.
 * @property timestamp The timestamp indicating when the task was created.
 */
@Parcelize
@Entity(tableName = TASK_TABLE)
data class TaskEntry(
    @PrimaryKey(autoGenerate = true)
    var id: Int,
    var title: String,
    var priority: Int,
    var timestamp: Long
):Parcelable